//PRODUCTS
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const GET_PRODUCT = 'GET_PRODUCT';
export const CLEAR_PRODUCT_EDITED = 'CLEAR_PRODUCT_EDITED';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const RESET_LIST_PRODUCTS = 'RESET_LIST_PRODUCTS';
export const FIND_PRODUCT = 'FIND_PRODUCT';
//COMMENTS
export const ADD_COMMENT = 'ADD_COMMENT';
//AUTHENTICATION
export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
//ERRORS
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';